/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.meteothink.imep.forms;

import org.meteothink.imep.verification.ContinuousMethod;
import org.meteothink.imep.verification.DichotomousMethod;
import org.meteothink.imep.verification.MethodType;
import org.meteothink.imep.verification.MultiCategoryMethod;
import org.meteothink.imep.verification.VerifyGroup;
import org.meteothink.imep.verification.VerifyMethod;

/**
 *
 * @author yaqiang
 */
public class FrmMethod extends javax.swing.JDialog {

    private VerifyGroup _group;
    private VerifyMethod _method;
    
    /**
     * Creates new form FrmMethod
     */
    public FrmMethod(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_MethodType = new javax.swing.JComboBox();
        jPanel_Dichotomous = new javax.swing.JPanel();
        jLabel_Threshold = new javax.swing.JLabel();
        jTextField_MinThreshold = new javax.swing.JTextField();
        jTextField_MaxThreshold = new javax.swing.JTextField();
        jLabel_Threshold1 = new javax.swing.JLabel();
        jPanel_MultiCategory = new javax.swing.JPanel();
        jLabel_Values = new javax.swing.JLabel();
        jTextField_Values = new javax.swing.JTextField();
        jButton_OK = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Method Type:");

        jComboBox_MethodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_MethodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MethodTypeActionPerformed(evt);
            }
        });

        jLabel_Threshold.setText("Min Threshold:");

        jTextField_MinThreshold.setText("null");

        jTextField_MaxThreshold.setText("null");

        jLabel_Threshold1.setText("Max Threshold:");

        javax.swing.GroupLayout jPanel_DichotomousLayout = new javax.swing.GroupLayout(jPanel_Dichotomous);
        jPanel_Dichotomous.setLayout(jPanel_DichotomousLayout);
        jPanel_DichotomousLayout.setHorizontalGroup(
            jPanel_DichotomousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DichotomousLayout.createSequentialGroup()
                .addComponent(jLabel_Threshold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_MinThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Threshold1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_MaxThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_DichotomousLayout.setVerticalGroup(
            jPanel_DichotomousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DichotomousLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DichotomousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DichotomousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Threshold1)
                        .addComponent(jTextField_MaxThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_DichotomousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Threshold)
                        .addComponent(jTextField_MinThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Values.setText("Values:");

        javax.swing.GroupLayout jPanel_MultiCategoryLayout = new javax.swing.GroupLayout(jPanel_MultiCategory);
        jPanel_MultiCategory.setLayout(jPanel_MultiCategoryLayout);
        jPanel_MultiCategoryLayout.setHorizontalGroup(
            jPanel_MultiCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(jPanel_MultiCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_MultiCategoryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_Values)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField_Values, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)))
        );
        jPanel_MultiCategoryLayout.setVerticalGroup(
            jPanel_MultiCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
            .addGroup(jPanel_MultiCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_MultiCategoryLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel_MultiCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Values, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Values))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton_OK.setText("OK");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_MultiCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_MethodType, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel_Dichotomous, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_MethodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Dichotomous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_MultiCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel)
                    .addComponent(jButton_OK))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        // TODO add your handling code here:
        MethodType methodType = (MethodType) this.jComboBox_MethodType.getSelectedItem();
        VerifyMethod method = new DichotomousMethod();
        switch (methodType) {
            case DICHOTOMOUS:
                DichotomousMethod dMethod = new DichotomousMethod();
                String minTstr = this.jTextField_MinThreshold.getText();
                String maxTstr = this.jTextField_MaxThreshold.getText();
                if (!minTstr.equalsIgnoreCase("null"))
                    dMethod.getDataRange().setMinThreshold(Double.parseDouble(minTstr));
                if (!maxTstr.equalsIgnoreCase("null"))
                    dMethod.getDataRange().setMaxThreshold(Double.parseDouble(maxTstr));
                method = dMethod;
            break;
            case MULTICATEGORY:
                MultiCategoryMethod mMethod = new MultiCategoryMethod();
                mMethod.setValues(this.jTextField_Values.getText());
                method = mMethod;
            break;
            case CONTINUOUS:
                method = new ContinuousMethod();
                break;
        }

        this._group.setVerifyMethod(method);
        this.dispose();
    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jComboBox_MethodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MethodTypeActionPerformed
        // TODO add your handling code here:
        if (this.jComboBox_MethodType.getItemCount() > 0){
            MethodType methodType = (MethodType)this.jComboBox_MethodType.getSelectedItem();
            switch (methodType){
                case DICHOTOMOUS:
                    this.jPanel_Dichotomous.setVisible(true);
                    this.jPanel_MultiCategory.setVisible(false);
                    if (this._method.getMethodType() == MethodType.DICHOTOMOUS){      
                        DichotomousMethod dMethod = (DichotomousMethod)this._method;
                        this.jTextField_MinThreshold.setText(String.valueOf(dMethod.getDataRange().getMinThreshold()));
                        this.jTextField_MaxThreshold.setText(String.valueOf(dMethod.getDataRange().getMaxThreshold()));
                    } else {
                        this.jTextField_MinThreshold.setText("null");
                        this.jTextField_MaxThreshold.setText("null");
                    }
                    break;
                case MULTICATEGORY:
                    this.jPanel_Dichotomous.setVisible(false);
                    this.jPanel_MultiCategory.setVisible(true);
                    if (this._method.getMethodType() == MethodType.MULTICATEGORY){
                        MultiCategoryMethod mMethod = (MultiCategoryMethod)this._method;
                        this.jTextField_Values.setText(mMethod.valuesToString());
                    } else {
                        this.jTextField_Values.setText("0.0;1.0");
                    }
                    break;
                case CONTINUOUS:
                    this.jPanel_Dichotomous.setVisible(false);
                    this.jPanel_MultiCategory.setVisible(false);
                    break;
            }
        }
    }//GEN-LAST:event_jComboBox_MethodTypeActionPerformed

    public void setVerifyGroup(VerifyGroup group) {
        _group = group;
        _method = group.getVerifyMethod();
        this.jComboBox_MethodType.removeAllItems();
        for (MethodType type : MethodType.values()) {
            this.jComboBox_MethodType.addItem(type);
        }
        this.jComboBox_MethodType.setSelectedItem(this._method.getMethodType());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmMethod dialog = new FrmMethod(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JComboBox jComboBox_MethodType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Threshold;
    private javax.swing.JLabel jLabel_Threshold1;
    private javax.swing.JLabel jLabel_Values;
    private javax.swing.JPanel jPanel_Dichotomous;
    private javax.swing.JPanel jPanel_MultiCategory;
    private javax.swing.JTextField jTextField_MaxThreshold;
    private javax.swing.JTextField jTextField_MinThreshold;
    private javax.swing.JTextField jTextField_Values;
    // End of variables declaration//GEN-END:variables
}
